site_name: persistproc Documentation
site_description: A shared process layer for the modern, multi-agent development workflow
site_url: https://persistproc.readthedocs.io/
repo_url: https://github.com/irskep/persistproc-mcp
repo_name: irskep/persistproc-mcp

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

nav:
  - Home: index.md
  - Installation: installation.md
  - Agent Configuration: configuring-agents.md
  - Prompting Tips: prompting-tips.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/irskep/persistproc-mcp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/persistproc/
  version:
    provider: mike