name: PR Docs Comment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  issues: write
  pull-requests: write
  actions: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for docs build
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const sha = context.payload.pull_request.head.sha;
            console.log(`PR #${prNumber}, SHA: ${sha}`);
            
            // Wait up to 5 minutes for docs workflow to complete
            let attempts = 0;
            let runId = null;
            
            while (attempts < 30 && !runId) {
              const { data: workflowRuns } = await github.rest.actions.listWorkflowRunsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'docs.yml',
                head_sha: sha,
                per_page: 5
              });
              
              const run = workflowRuns.workflow_runs.find(r => r.status === 'completed' && r.conclusion === 'success');
              if (run) {
                runId = run.id;
                console.log(`Found completed docs workflow run: ${runId}`);
                break;
              }
              
              console.log(`Attempt ${attempts + 1}: No completed docs workflow found yet, waiting...`);
              await new Promise(resolve => setTimeout(resolve, 10000)); // Wait 10 seconds
              attempts++;
            }
            
            if (!runId) {
              console.log('No completed docs workflow found after 5 minutes');
              return;
            }
            
            // Post the comment
            const repo = `${context.repo.owner}/${context.repo.repo}`;
            const artifactUrl = `https://github.com/${repo}/actions/runs/${runId}#artifacts`;
            const body = `📚 Documentation Preview

The documentation has been built for this PR. You can download it here:

🔗 **[Download Documentation Artifact](${artifactUrl})**

**Instructions:**
1. Click the link above
2. Download the \`docs-pr-${prNumber}\` artifact
3. Extract the ZIP file
4. Open \`index.html\` in your browser

*Note: You must be logged in to GitHub to download artifacts.*`;

            try {
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
              });
              
              const existing = comments.find(c => 
                c.user.login === 'github-actions[bot]' && 
                c.body.includes('📚 Documentation Preview')
              );

              if (existing) {
                console.log(`Updating existing comment ${existing.id}`);
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existing.id,
                  body,
                });
              } else {
                console.log(`Creating new comment on PR #${prNumber}`);
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body,
                });
              }
              console.log('Comment posted successfully');
            } catch (error) {
              console.error('Error posting comment:', error);
              throw error;
            }