name: PR Docs Comment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post / update comment with download link
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const runId = process.env.GITHUB_RUN_ID;
            const repo = `${context.repo.owner}/${context.repo.repo}`;
            const body = `📚 Documentation Preview\n\nDownload the built documentation artifact for this PR:\n\nhttps://github.com/${repo}/actions/runs/${runId}\n\nAfter downloading, extract the ZIP and open index.html in your browser.`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            const existing = comments.find(c => c.user.login === 'github-actions[bot]' && c.body.startsWith('📚 Documentation Preview'));

            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body,
              });
            }